# Generated by Django 3.2.5 on 2021-07-16 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='accountType',
            field=models.CharField(choices=[('PREMIUM', 'premium'), ('STANDARD', 'standard'), ('BASIC', 'basic'), ('FREE', 'free')], default='FREE', max_length=50),
        ),
        migrations.CreateModel(
            name='ImageCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_processed', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
