# Generated by Django 3.2.5 on 2021-07-17 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='accountType',
            field=models.CharField(choices=[('3', 'premium'), ('2', 'standard'), ('1', 'basic'), ('FREE', 'free')], default='FREE', max_length=50),
        ),
        migrations.CreateModel(
            name='SeoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
