# Generated by Django 3.2.5 on 2021-07-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210718_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='acessOngen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consumers',
            name='acessOnseo',
            field=models.BooleanField(default=False),
        ),
    ]
