# Generated by Django 3.2.5 on 2021-07-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210718_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='free_image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumers',
            name='premium_image_count',
            field=models.IntegerField(default=0),
        ),
    ]
