# Generated by Django 3.2.5 on 2021-07-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210723_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumers',
            name='paid',
        ),
    ]
