# Generated by Django 3.2.5 on 2021-07-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_consumers_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumers',
            name='credits',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='consumers',
            name='durations',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='consumers',
            name='accountType',
            field=models.CharField(choices=[('4', 'custom'), ('3', 'premium'), ('2', 'standard'), ('1', 'basic'), ('FREE', 'free')], default='FREE', max_length=50),
        ),
    ]
