# Generated by Django 3.2.5 on 2021-07-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210724_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumers',
            old_name='credits',
            new_name='basic_credits',
        ),
        migrations.AddField(
            model_name='consumers',
            name='premium_credits',
            field=models.IntegerField(default=0),
        ),
    ]
