# Generated by Django 3.2.5 on 2021-07-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210724_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumers',
            old_name='free_image_count',
            new_name='basic_image_count',
        ),
    ]
