# Generated by Django 3.2.5 on 2021-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_free_image_count_consumers_basic_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basic_credits',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='premium_credits',
            field=models.IntegerField(default=0),
        ),
    ]
