# Generated by Django 3.2.5 on 2021-07-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210724_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageCount',
        ),
        migrations.DeleteModel(
            name='SeoImage',
        ),
    ]
