# Generated by Django 3.2.5 on 2021-08-06 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_verifycode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('times', models.IntegerField(default=30)),
                ('credits', models.IntegerField(default=100)),
                ('license_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
