# Generated by Django 3.2.5 on 2021-08-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='credits',
            new_name='basic_credits',
        ),
        migrations.AddField(
            model_name='license',
            name='premium_credits',
            field=models.IntegerField(default=100),
        ),
    ]
