# Generated by Django 3.2.5 on 2021-08-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210806_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='premium_credits',
            field=models.IntegerField(default=20),
        ),
    ]
