# Generated by Django 3.2.5 on 2021-08-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_consumers_premium_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='acessOnseo',
            field=models.BooleanField(default=True),
        ),
    ]
